### ISSUE TITLE
Pitfalls of AI 

### ISSUE THREAD

**Issue by Shashi456** [daviddao/awful-ai#15]
Can we add biases that are made within ai ? I think that should be added because these models are trained on data curated by humans which on some level just portray the biases we have inherently. 

And on the other hand, I think one section of ai research that belongs here is adversarial examples, which is very relevant in the case of autonomous car safety. Since these adversarial examples lead the neural net to misclassify and in some cases also distort the input image enough to not  detect an object at all .

**Comment by Shashi456** [comment]
Yeah I don't mind, but how do you think I should structure it, because purely adding papers would result into a huge list.

**Comment by daviddao** [comment]
I think it makes sense to just add a paragraph (like algorithm bias & fairness). If you submit the PR I can adjust it :)

**Comment by daviddao** [comment]
Closing with #16
