### ISSUE TITLE
Predicting mass (anti-Trump) protests

### ISSUE THREAD

**Issue by polyzen** [daviddao/awful-ai#18]
https://motherboard.vice.com/en_us/article/7x3g4x/pentagon-wants-to-predict-anti-trump-protests-using-social-media-surveillance

**Comment by daviddao** [comment]
Wow! This is probably one of the worst use cases of surveillance I ever read about. Thanks for sharing! Do you want to submit a PR or should I do it?

**Comment by polyzen** [comment]
I haven't yet read through the article. Perhaps you spotted a good description to use?

**Comment by buoyantair** [comment]
Omg what the f are these people up to

**Comment by daviddao** [comment]
Added with d24e49120f71cabadfc66a0735a3c9607f5358ab - let's turn this into a discussion forum instead! It's extremly awful!
