### ISSUE TITLE
[SUGGESTION] Get discriminated while flying

### ISSUE THREAD

**Issue by twsI** [daviddao/awful-ai#27]
The following [article](https://theintercept.com/2018/12/03/air-travel-surveillance-homeland-security/) shows an other AI, that might discriminate people by trying to predict, who on the plane is a terrorist. Feel free to add it to the list, if you think, that it qualifies for this repo.
Cheers

**Comment by daviddao** [comment]
Wow, yes that's more than horrible - I'll review it and add it as PR

**Comment by daviddao** [comment]
Closing with 738cfec
