### ISSUE TITLE
Let's make this Awful list Awesome

### ISSUE THREAD

**Issue by ddelange** [daviddao/awful-ai#35]
Since this is such an important list, let's maybe make it [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)?

**Comment by KOLANICH** [comment]
No. Rules of `Awesome` is that the things listed must be awesome. Things listed here are mostly not awesome.

**Comment by daviddao** [comment]
I agree with @KOLANICH. I'm a huge fan of awesome lists. However, putting an awesome button on it would misguide the purpose of this list (displaying awful misuses of technology)

**Comment by KOLANICH** [comment]
>misuses of technology

There ain't no such a thing as misuse of technology. Though there is such a thing as immoral use.

**Comment by ddelange** [comment]
>Things listed here are mostly not awesome.

I'd say it's time to close this. Feel free to re-open/continue discussion :)
