### ISSUE TITLE
Is the application of A.I. to empower fossil fuel industry awful in light of climate change?

### ISSUE THREAD

**Issue by daviddao** [daviddao/awful-ai#36]
**Artificial Intelligence is one of the fossil fuel industry's key technologies.**

The first time I learned about this was [by this article](https://medium.com/@AINowInstitute/ai-and-climate-change-how-theyre-connected-and-what-we-can-do-about-it-6aa8d0f5b32c) from the AINow Institute.

Vox just recently published an [informative video](https://www.youtube.com/watch?v=v3n8txX3144) about how Google, Amazon, and Microsoft having contracts with big players in the fossil fuel industry - even going so far in investing massive amounts of money [in organizations that actively campaign against climate legislation](https://amp.theguardian.com/environment/2019/oct/11/google-contributions-climate-change-deniers?__twitter_impression=true), and promoting climate change denial.

At NeurIPS (our biggest scientific A.I. venue), several attendees of fossil fuel companies attended the conference and tried to hire A.I. people. (WiML (Women in Machine Learning) was even sponsored by Shell!)

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Thank you sponsors 📣<a href="https://twitter.com/hashtag/WiML?src=hash&amp;ref_src=twsrc%5Etfw">#WiML</a> is thankful to our Gold sponsors <a href="https://twitter.com/amazon?ref_src=twsrc%5Etfw">@amazon</a><br> <a href="https://twitter.com/Microsoft?ref_src=twsrc%5Etfw">@Microsoft</a> <a href="https://twitter.com/splunk?ref_src=twsrc%5Etfw">@splunk</a> <a href="https://twitter.com/Shell?ref_src=twsrc%5Etfw">@Shell</a> <a href="https://twitter.com/IntelAI?ref_src=twsrc%5Etfw">@IntelAI</a> <a href="https://twitter.com/unity3d?ref_src=twsrc%5Etfw">@unity3d</a><br> <a href="https://twitter.com/NoodleAI?ref_src=twsrc%5Etfw">@NoodleAI</a> <a href="https://twitter.com/Twitter?ref_src=twsrc%5Etfw">@Twitter</a> and <a href="https://twitter.com/nvidia?ref_src=twsrc%5Etfw">@nvidia</a> for all their support in making this event big.<a href="https://twitter.com/hashtag/WiML2019?src=hash&amp;ref_src=twsrc%5Etfw">#WiML2019</a> <a href="https://twitter.com/hashtag/NeurIPS2019?src=hash&amp;ref_src=twsrc%5Etfw">#NeurIPS2019</a> 🎉🎉 <a href="https://t.co/KffOGEOqKd">pic.twitter.com/KffOGEOqKd</a></p>&mdash; WiML (@WiMLworkshop) <a href="https://twitter.com/WiMLworkshop/status/1201612992837632000?ref_src=twsrc%5Etfw">December 2, 2019</a></blockquote>

[Just 20 fossil fuel companies are responsible for 1/3rd of all emissions.](https://www.theguardian.com/environment/2019/oct/09/revealed-20-firms-third-carbon-emissions) There is no scientific scenario where we can prevent the climate crisis without rapid decarbonization. 

**Question: Can we consider A.I. applications for the fossil fuel industry as awful? Would it make sense to create a new category?**

**Comment by KOLANICH** [comment]
Νο more than application A.I. to healthcare and food industry (no humans - no problems ;).

**Comment by daviddao** [comment]
Resolved with https://github.com/daviddao/awful-ai/commit/9ef9a5fb7362bed02bb2b1c85e625b096c1fc7d1
