### ISSUE TITLE
AI scams, so terrible they aren't even AI

### ISSUE THREAD

**Issue by edwardabraham** [daviddao/awful-ai#4]
This is a usefully depressing list. How about a category for AI scams—people pretending to be using AI to make sales, get money out of investors, and confuse people. A bizarre medical scam surfaced in New Zealand last year, run by the Terrible Foundation:
https://thespinoff.co.nz/the-best-of/06-03-2018/the-mystery-of-zach-new-zealands-all-too-miraculous-medical-ai/

**Comment by daviddao** [comment]
I think that's an awesome idea! There is so much scam around AI right now. We could list it under a category called '**Scams**' - those send crypto twitter bots could also be part of that category! Feel free to submit a PR!

**Comment by daviddao** [comment]
In the process of curating a list of intentionally overpromising projects and **scams**. Help wanted :) - what are some of the worst things you guys have heard about and claims which you know they are false!

**Comment by tedivm** [comment]
There's always [the original mechanical turk](https://en.wikipedia.org/wiki/The_Turk).

**Comment by daviddao** [comment]
I added a PR for this. @edwardabraham feel free to review it! https://github.com/daviddao/awful-ai/pull/23
